# Generated by Django 4.0.4 on 2022-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_alter_women_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название статьи'),
        ),
    ]
